; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = native

[base]
lib_deps = 
	m5stack/M5Unified@0.2.13
	lvgl/lvgl@9.5.0
build_flags =
    -DLV_CONF_SKIP
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_COLOR_DEPTH=8
    -DLV_DPI_DEF=234
	-DLV_USE_THEME_DEFAULT=0
	-DLV_USE_THEME_SIMPLE=0
	-DM5GFX_ROTATION=0
	-DM5GFX_BOARD=board_M5PaperS3

[env:target]
extends = base
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
build_flags = ${base.build_flags}
	-DESP32S3
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

[env:native]
extends = base
platform = native
build_type = debug
build_flags = ${base.build_flags}
	-O0 -std=c++17 -lSDL2
	-I"/usr/local/include/SDL2"
	-L"/usr/local/lib"
	-I"${sysenv.HOMEBREW_PREFIX}/include/SDL2"
	-L"${sysenv.HOMEBREW_PREFIX}/lib"
	-DM5GFX_SHOW_FRAME
	-DM5GFX_BACK_COLOR=0x222222u
